spring.application.name=GestionDocumentosApi

server.port=8087

spring.datasource.SQL.url=jdbc:sqlserver://DESKTOP-HBLC4DM\\MSSQL2022:1433;databaseName=DB_EASYCLOUD_GESTIONDOCUMENTOS;encrypt=true;trustServerCertificate=true;
spring.datasource.SQL.username=sa
spring.datasource.SQL.password=admin123
spring.datasource.SQL.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===================================================================================
# OCULTAR SCHEMAS EN EL SWAGGER
springdoc.swagger-ui.default-models-expand-depth=-1
springdoc.swagger-ui.doc-expansion=none
# ===================================================================================

# ===================================================================================
# JWT Configuration
jwt.secret=SeyaCloudSecretKeyGestionGeneralAndValidacionInteraccionesModulosSistema
jwt.expiration=86400000
# ===================================================================================

# ===================================================================================
# Encriptacion Password
app.security.password-seed=dataBusiness$2026*_Desarrollo_Sistemas_Area_TI_dmkweb_secret_key_SEYA
encriptacion.password.min-length=8
encriptacion.password.require-uppercase=true
encriptacion.password.require-lowercase=true
encriptacion.password.require-numbers=true
# ===================================================================================

# ===================================================================================
# Configuracion REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
# ===================================================================================

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
